darkHeresyCharacterSheets/darkHeresyCharacterSheets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('room_service.urls'))
]

darkHeresyCharacterSheets/room_service/urls.py
from django.conf.urls import url
from room_service import views

app_name = "room_service"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('login', views.login_user, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^room/join$', views.room_join_view, name='room_join'),
    url(r'^room/create$', views.room_create, name='room_create'),
    url(r'^room/(?P<room>[0-9]+)$', views.room_view, name='room_view'),
    url(r'^card', views.card_json, name='card')
]

darkHeresyCharacterSheets/room_service/models.py
from django.db import models
from django.contrib.auth.models import User

# Character model used to store information on user's characters.
class Character(models.Model):
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(User)

darkHeresyCharacterSheets/room_service/forms/room_form.py
from django import forms
from room_service.models import Room

class RoomForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Room
        fields = ('name',)

darkHeresyCharacterSheets/room_service/forms/user_form.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password',)

darkHeresyCharacterSheets/room_service/views/auth_views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext

from room_service.forms import UserForm


# Create your views here.
def register(request):
    '''Handles the creation of a new user for authentication
    Method arguments:
      request -- The full HTTP request object
    '''

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # Create a new user by invoking the `create_user` helper method
    # on Django's built-in User model
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        return login_user(request)

    elif request.method == 'GET':
        user_form = UserForm()
        template_name = 'register.html'
        return render(request, template_name, {'user_form': user_form})


def login_user(request):
    '''Handles the creation of a new user for authentication
    Method arguments:
      request -- The full HTTP request object
    '''

    # Obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':

        # Use the built-in authenticate method to verify
        username=request.POST['username']
        password=request.POST['password']
        authenticated_user = authenticate(username=username, password=password)

        # If authentication was successful, log the user in
        if authenticated_user is not None:
            login(request=request, user=authenticated_user)
            return HttpResponseRedirect('/')

        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {}, {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")


    return render(request, 'login.html', {}, context)

# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage. Is there a way to not hard code
    # in the URL in redirects?????
    return HttpResponseRedirect('/')

darkHeresyCharacterSheets/room_service/views/card_json.py
from django.shortcuts import render
from django.http import JsonResponse
from room_service.models import Card

def card_json (request):

    if request.method == 'GET':
        card = Card.objects.all().values()
        card_list = list(card)
        json_response = JsonResponse(card_list, safe=False)
        return json_response

darkHeresyCharacterSheets/room_service/views/index_view.py
from django.shortcuts import render, HttpResponseRedirect
from django.template import RequestContext


def index(request):

    if request.user.is_authenticated:
        template_name = 'index.html'
        return render(request, template_name)
    else:
        return HttpResponseRedirect('login')
        

darkHeresyCharacterSheets/room_service/views/room_create_view.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext

from room_service.models import Room
from room_service.forms import RoomForm

@login_required
def room_create(request):

    if request.method == 'GET':
        room_form = RoomForm()
        template_name = 'room_create.html'
        return render(request, template_name, {'room_form': room_form})

    elif request.method == 'POST':
        form_data = request.POST

        r = Room(
            name = form_data['name'],
        )
        r.save()
        r.users.add(request.user)
        return HttpResponseRedirect(f'/room/{r.id}')

darkHeresyCharacterSheets/room_service/views/room_join_view.py
from django.shortcuts import render
from django.template import RequestContext
from room_service.models import Room
from django.contrib.auth.decorators import login_required


@login_required
def room_join_view(request):
    template_name = 'room_join.html'
    rooms = Room.objects.all()
    return render(request, template_name, {'rooms': rooms})

darkHeresyCharacterSheets/room_service/views/room_view.py
from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from room_service.models import Room


@login_required
def room_view(request, room):

     if request.method == 'GET':
        template_name = 'room.html'
        current_room = Room.objects.get(pk=room)
        current_users = current_room.users.all()

        return render(request, template_name, {'current_room': current_room, 'current_users': current_users})

darkHeresyCharacterSheets/room_service/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sector 86</title>
    <link href='https://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <nav>
        {% if user.is_authenticated %}
            <form action="{% url 'room_service:logout' %}" method="get">
                <input type="submit" value="Logout">
            </form>
            <form action="{% url 'room_service:room_create' %}" method="get">
                <input type="submit" value="Create New Room">
            </form>
            <form action="{% url 'room_service:room_join' %}" method="get">
                    <input type="submit" value="Join Room">
            </form>
        {% else %}
            <form action="{% url 'room_service:login' %}" method="get">
                <input type="submit" value="Login">
            </form>
            <form action="{% url 'room_service:register' %}" method="get">
                <input type="submit" value="Register">
            </form>
        {% endif %}
    </nav>
    <div id='content'>
        {% block content %}
            <h1>Welcome to Sector 86</h1>
            {% if user.is_authenticated %}
                <p>Welcome to Sector 86! Create a room to start building your station!</p>
                <p>Note: This site requires Javascript. If you have disabled Javascript, please enable it for this site.</p>
            {% endif %}
        {% endblock %}
    </div>
</body>
</html>

darkHeresyCharacterSheets/room_service/templates/login.html
{% extends 'index.html' %}
{% block content %}
    <h1>Login to Dark Heresy Character Sheet</h1>
    <form id="login_form" method="post" action="{% url 'room_service:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />

        <input type="submit" value="submit" />
    </form>
    <p>No account?</p>
    <a href="{% url 'room_service:register' %}">Register Here</a>
{% endblock %}

darkHeresyCharacterSheets/room_service/templates/register.html
{% extends 'index.html' %}
{% block content %}
    <h1>Register with Sector 86</h1>

    {% if registered %}
    <strong>Thank you for registering!</strong>
    <a href="{% url 'room_service:index' %}">Return to the homepage.</a><br />
    {% else %}
    <strong>Register here!</strong><br />

    <form id="user_form" method="post" action="{% url 'room_service:register' %}"
            enctype="multipart/form-data">

        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
            (<p>) element. This ensures each element appears on a new line,
            making everything look neater. -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
{% endblock %}

darkHeresyCharacterSheets/room_service/templates/room.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block content %}
    <div id='header-info'> 
        <div id='room-info'>
            <h1>{{current_room.name}}</h1>
            <h5>Room ID# <span id='room-id'>{{current_room.id}}</span></h5>
        </div>
        <div id='multiplayer-info'>
        {% for user in current_users %}
            <h4>Players:</h4>
            <p>{{user.username}}</p>
        {% endfor %}
        <input type='button' id='show-opponent-area' value="Show Opponent's Station">
        </div>
    </div>   
    <div id='play-hints'>
        <h5>Click on the library to start drawing cards or gaining credits. Click on a card to discard it or complete missions and contracts.</h5>
        <h5>For the rules, <a href="https://games.invincible.ink/sector86-rules.pdf" target="_blank">click here</a> <input type='button' value='Hide' id='hide-hints' /></h5>
    </div>
    <div id="card-area">
        <div id="play-area">
            <div id='draw-area' class='column'>
                <h3>Library</h3>
                <img src="{% static 'card_images/CardBack.png' %}" id="library" alt="Library"/>
                <br />
                <input type="button" value="Take Cards" id="take-cards" />
                <br />
                <div id='drawn-cards-area'>

                </div>
            </div>
            <div id='credit-area' class='column'>
                    <h3>Credits</h3>
                    <div id='station-Credit-area'>
                    </div>
                </div>
            <div id='station-area' class='column'>
                <h3>Station</h3>
                <div>
                    <h4>Ships</h4>
                    <div id='station-Ship-area'>

                    </div>
                </div>
                <div>
                    <h4>Crew</h4>
                    <div id='station-Crew-area'>

                    </div>
                </div>
                <div>
                    <h4>Facilities</h4>
                    <div id='station-Facility-area'>

                    </div>
                </div>
                <div>
                        <h4>Completed Missions</h4>
                        <div id='station-Mission-area'>

                        </div>
                </div>
            </div>
            <div id='levy-area' class='column'>
                <h3>Levies</h3>
                <div id='station-Levy-area'>

                </div>
            </div>
            <div id='mission-area' class='column'>
                <h3>Missions</h3>
            </div>
        </div>
        <div id='discarded-area-parent'>
            <h3>Discarded Cards</h3>
            <div id='discard-area'>
            </div>
        </div>
    </div>
    <div id='opponent-area'>
        <h1>Opponent Station</h1>
        <input type='button' id='hide-opponent-area' value='Close' />
        <div id="opponent-play-area">
            <div id='opponent-draw-area' class='column'>
                <h3>Drawn Cards</h3>
                <div id='opponent-drawn-cards-area'>

                </div>
            </div>
            <div id='opponent-credit-area' class='column'>
                    <h3>Credits</h3>
                    <div id='opponent-station-Credit-area'>
                    </div>
                </div>
            <div id='opponent-station-area' class='column'>
                <h3>Station</h3>
                <div>
                    <h4>Ships</h4>
                    <div id='opponent-station-Ship-area'>

                    </div>
                </div>
                <div>
                    <h4>Crew</h4>
                    <div id='opponent-station-Crew-area'>

                    </div>
                </div>
                <div>
                    <h4>Facilities</h4>
                    <div id='opponent-station-Facility-area'>

                    </div>
                </div>
                <div>
                        <h4>Completed Missions</h4>
                        <div id='opponent-station-Mission-area'>

                        </div>
                </div>
            </div>
            <div id='opponent-levy-area' class='column'>
                <h3>Levies</h3>
                <div id='opponent-station-Levy-area'>

                </div>
            </div>
        </div>
    </div>

    </div>
    <script>
        localStorage.setItem('user_id', '{{ user.id }}')
        localStorage.setItem('user_name', '{{ user }}')
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'scripts/bundle.js' %}"></script>
{% endblock %}

darkHeresyCharacterSheets/room_service/templates/room_create.html
{% extends 'index.html' %}
{% block content %}
    <h1>Create Room</h1>


    <form action="{% url 'room_service:room_create' %}" method="post">
        {% csrf_token %}
        {{ room_form.as_p }}
        <input type="submit" value="Create Room" />
    </form>
{% endblock %}

darkHeresyCharacterSheets/room_service/templates/room_join.html
{% extends 'index.html' %}
{% block content %}
    {% for room in rooms%}
        <li><a href="{% url 'room_service:room_view' room.id %}">{{ room.name }}</a></li>
    {% endfor %}
{% endblock %}